server:
  port: 8900


eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
  instance:
    hostname: 127.0.0.1


spring:
  application:
    name: testdemo
