spring:
    application:
      name: Gateway
    cloud:
        gateway:
            discovery:
                locator:
                  enabled: true
                  lower-case-service-id: true
            routes:
            - id: musicservice
              uri: lb://musicservice
              predicates:
                - Path=/api/music/**
              filters: StripPrefix=1 #忽略第一层
            - id: userservice
              uri: lb://userservice
              predicates:
              - Path=/api/user/**
              filters: StripPrefix=1 #忽略第一层
            - id: commentservice
              uri: lb://commentservice
              predicates:
              - Path=/api/comment/**
              filters: StripPrefix=1 #忽略第一层
server:
    port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
  instance:
    hostname: localhost

